### ISSUE TITLE
Dispense info is disconnected

### ISSUE THREAD

**Issue by akirakakar** [umed-jp/umed#15] opened 2024-03-06 07:54 UTC
Dispense info is disconnected. 
1. We want to quickly fix this specific instance
2. We want to fix the root cause

[AB#3758](https://dev.azure.com/UMedInc/d5d481fe-0809-4400-a9e9-d50f4dd3bb46/_workitems/edit/3758)

**Comment by akirakakar** [comment] 2024-03-06 08:43
PatientID: 85117a1e-8e45-42f9-bdd2-b1e2b6a77715
EncounterID: 4c109e53-8e73-4cc6-8456-6b66dd3956a8

**Comment by castilloglenn** [comment] 2024-03-07 01:08
![image](https://github.com/umed-jp/umed/assets/55197203/1c33663b-9f7c-4b1b-b0ca-d42e498a1705)

**Comment by castilloglenn** [comment] 2024-03-07 03:06
## Re-added the prescription details

![image](https://github.com/umed-jp/umed/assets/55197203/c88edeb3-4024-4574-8b35-3b77e9f2787b)

Now working on fixing the root cause

**Comment by castilloglenn** [comment] 2024-03-07 07:08
I can reproduce this one, but still fixing the root cause.

As a practitioner,
1. accept an appointment
2. add clinical note
3. change acquisition method to `No Medications`
4. end the encounter
5. then quickly add medication
6. if the api call for ending the appointment and the new medication somehow goes at the backend at the same time, the medication will not be present at the `OrdersPage` but is present in the FHIR resource.

**Comment by castilloglenn** [comment] 2024-03-07 08:20
## Bug demo

https://github.com/umed-jp/umed/assets/55197203/3fa5214e-ab81-4b9a-9c7a-799cee63835c

**Comment by castilloglenn** [comment] 2024-03-12 03:44
merged fixes

**Closed as completed by castilloglenn** 2024-03-12 03:44 UTC
Labels: bug, sev3
