### ISSUE TITLE
Walk-In was not turned on until the doctor refreshes the screen.

### ISSUE THREAD

**Issue by akirakakar** [umed-jp/umed#92] opened 2024-05-17 00:33 UTC
Akira has posted an issue in Discord

<@567680071628881921> Walk-In was not turned on until the doctor refreshes the screen.

- Patient(I) oberved that walk-in was not ON
- Staff(I) log-in as a doctor to see if queue was on or not (This feature is required)
- Staff observed that it was ON and also Patient observed that walk-in was turned on
- the doctor shared the screen and queue was ON but when staff closed the doctor's account, walk-in was not turned ON anymore
- Staff turned off the doctor's account and ask the doctor to refresh the screen
- Patient observed that walk-in was ON

**Comment by Grrom** [comment] 2024-05-17 01:01
I could not reproduce in dev,
my guess is that the doctor logged first before the service was deployed to prod so it did not track their client as online.

then staff logs in to doctor's account and that was the only client that was tracked as online.
then, when staff closes their client, the service saw that there were no more clients for the doctors so the doctor was considered offline.

here's a video of me trying the exact steps that happened in prod

https://github.com/umed-jp/umed/assets/62323308/eeca895b-9d33-4fd2-9e64-81b75fad09c8

**Comment by Grrom** [comment] 2024-05-17 01:02
discord thread
- https://discord.com/channels/1161110836635508778/1176408561379725372/1240821543588855949

**Comment by Grrom** [comment] 2024-05-17 01:04
this might have been just because of the timing the service was deployed and the time doctor first logged in.
if so, then it's not actually an issue.

but I'm leaving the issue open for now and investigate a bit further until it happens again

**Comment by Grrom** [comment] 2024-05-22 10:07
looks like the reason was the client failed to reconnect so it only retried to re-connect when the page was refreshed

- https://github.com/umed-jp/practitioner-frontend-ts/pull/550
- https://github.com/umed-jp/KitsuneWebsocket/pull/5

I've investigated and this seems to be the cause,
the PR has been merged but I think we should keep this issue open until we confirm that it's really fixed

**Comment by castilloglenn** [comment] 2024-06-04 02:24
1 week passed and not reported again, will be closing 🙇🏽

**Closed as completed by castilloglenn** 2024-06-04 02:24 UTC
Labels: bug, sev3
