### ISSUE TITLE
Some of appointments are not sent to orders again. This was happening before but I don't think it was one time issue.

### ISSUE THREAD

**Issue by akirakakar** [umed-jp/umed#62] opened 2024-04-16 06:05 UTC
Akira has posted an issue in Discord

<@906813918142402592> 
Some of appointments are not sent to orders again. This was happening before but I don't think it was one time issue.

**Comment by fauortiz** [comment] 2024-04-16 06:30
possibly a duplicate of:
- https://github.com/umed-jp/umed/issues/58 ?

**Closed as completed** 2024-04-29 17:08 UTC
Labels: bug, sev3
