### ISSUE TITLE
Walk-In is turned on all the time

### ISSUE THREAD

**Issue by akirakakar** [umed-jp/umed#95] opened 2024-05-20 09:03 UTC
Akira has posted an issue in Discord

Walk-In is turned on all the time

<@&1219098225458282546>

**Comment by Grrom** [comment] 2024-05-22 10:05
- https://github.com/umed-jp/practitioner-frontend-ts/pull/550
- https://github.com/umed-jp/KitsuneWebsocket/pull/5

I've investigated and this seems to be the cause,
the PR has been merged but I think we should keep this issue open until we confirm that it's really fixed

**Comment by castilloglenn** [comment] 2024-06-04 02:24
1 week passed and not reported again, will be closing 🙇🏽

**Closed as completed by castilloglenn** 2024-06-04 02:24 UTC
Labels: bug, sev2
