### ISSUE TITLE
end encounter doesn't update the backend

### ISSUE THREAD

**Issue by akirakakar** [umed-jp/umed#22] opened 2024-03-07 16:11 UTC
Raf23 has posted an issue in Discord

i tried clicking the end encounter on appointment details it does process it updates the status on the appointment detail but it doesnt update on the backend and the list

**Comment by castilloglenn** [comment] 2024-03-08 03:20
for this one this is a correlated repercussion of the root cause of this other bug:
- https://github.com/umed-jp/umed/issues/15

**Comment by castilloglenn** [comment] 2024-03-08 07:03
The issue is with the syncing of statuses in the frontend.

**Comment by castilloglenn** [comment] 2024-03-08 07:04
These two are related
- https://github.com/umed-jp/umed/issues/23

**Comment by castilloglenn** [comment] 2024-03-12 08:39
fix merged

**Closed as completed by castilloglenn** 2024-03-12 08:39 UTC
Labels: bug, sev3
