### ISSUE TITLE
appointment was not reflected in order

### ISSUE THREAD

**Issue by akirakakar** [umed-jp/umed#54] opened 2024-04-03 07:45 UTC
Akira has posted an issue in Discord

<@865828035340795915> <@520447604266631172> 
https://practitioner-portal.web.app/appointments/3335d46d-839f-4863-b845-d74c219695f8
This patient's result is not reflected in the order page.

**Comment by fauortiz** [comment] 2024-04-04 01:01
duplicate of:
- https://github.com/umed-jp/umed/issues/43

the logger for this was merged to dev, but not in prod. I've now promoted it to prod.

**Learning**
 Only close issues in production when the solutions are merged to prod

**Closed as completed by fauortiz** 2024-04-04 01:01 UTC
Labels: bug, duplicate
