### ISSUE TITLE
the encounter is already finished but still on this component

### ISSUE THREAD

**Issue by akirakakar** [umed-jp/umed#23] opened 2024-03-07 17:35 UTC
Raf23 has posted an issue in Discord

the encounter is already finished but still on this component

**Comment by castilloglenn** [comment] 2024-03-08 03:18
for this one this is a correlated repercussion of the root cause of this other bug:
- https://github.com/umed-jp/umed/issues/15

**Comment by castilloglenn** [comment] 2024-03-08 07:02
The issue is with the syncing of statuses in the frontend.

**Comment by castilloglenn** [comment] 2024-03-12 08:39
fix merged

**Closed as completed by castilloglenn** 2024-03-12 08:39 UTC
Labels: bug, sev3
